name: Mirror to Gitee

on: [push, delete, create]

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: 'git@github.com:qxy-fe/fe-docs.git'
          destination-repo: 'git@gitee.com:ntnyq/fe-docs.git'

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@master
        with:
          gitee-username: ntnyq
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: ntnyq/fe-docs
          branch: gh-pages
